// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type TodoEntry struct {
	ID         int64
	Content    string
	IsDone     sql.NullBool
	IsArchived sql.NullBool
	TableID    int64
}

type TodoTable struct {
	ID    int64
	Title string
}
